<!-- #include file="Objects/GUIDClass.asp" -->
<!-- #include file="Objects/UtilClass.asp" -->
<!-- #include file="Objects/Base64Class.asp" -->
<!-- #include file="Objects/CacheClass.asp" -->
<!-- #include file="Objects/DBManagerClass.asp" -->
<!-- #include file="Objects/CountryClass.asp" -->
<!-- #include file="Objects/UserPreferenceClass.asp" -->
<!-- #include file="Objects/UserClass.asp" -->
<!-- #include file="Objects/CategoryClass.asp" -->
<!-- #include file="Objects/MenuClass.asp" -->
<!-- #include file="Objects/ExceptionClass.asp" -->
<!-- #include file="Objects/LanguageClass.asp" -->
<!-- #include file="Objects/TargetClass.asp" -->
<!-- #include file="Objects/LogClass.asp" -->
<!-- #include file="Objects/Page4TemplateClass.asp" -->
<!-- #include file="Objects/TemplateClass.asp" -->
<!-- #include file="Objects/ImageUploadClass.asp" -->
<%
'<!--nsys-inc2-->
%>
<!-- #include file="Objects/TaxsClass.asp" -->
<!-- #include file="Objects/TaxsGroupClass.asp" -->
<!-- #include file="Objects/PaymentClass.asp" -->
<!-- #include file="Objects/PaymentFieldClass.asp" -->
<!-- #include file="Objects/PaymentModuleClass.asp" -->
<!-- #include file="Objects/PaymentTransactionClass.asp" -->
<!-- #include file="Objects/BillsClass.asp" -->
<!-- #include file="Objects/CurrencyClass.asp" -->

<!-- #include file="Objects/UserGroupClass.asp" -->
<!-- #include file="Objects/VoucherClass.asp" -->
<!-- #include file="Objects/MarginDiscountClass.asp" -->
<!-- #include file="Objects/BusinessRulesClass.asp" -->
<!-- #include file="Objects/File4ProductsClass.asp" -->
<!-- #include file="Objects/ProductsClass.asp" -->
<!-- #include file="Objects/Products4OrderClass.asp" -->
<!-- #include file="Objects/Bills4OrderClass.asp" -->
<!-- #include file="Objects/OrderClass.asp" -->
<%
'<!---nsys-inc2-->
%>
<!-- #include file="Objects/CommentsClass.asp" -->
<!-- #include file="Objects/LocalizationClass.asp" -->

<!-- #include file="InitData.inc" -->
