	<div id="header">
		<div id="top-bar">
			<div id="top-bar-logo"><!--nsys-head1--><a href="<%=base_url&Application("srt_default_server_name")&Application("baseroot")&"/default.asp"%>"><img src="<%=Application("baseroot")&"/common/img/logo.png"%>" hspace="2" vspace="0" border="0" align="left" alt="<%=lang.getTranslated("portal.commons.label.home_page")%>"></a><!---nsys-head1--></div>
			<div id="top-bar-search"><!-- #include virtual="/public/layout/addson/search/search_widget.inc" --></div>
			<div id="top-bar-lenguage"><!-- #include virtual="/public/layout/addson/langs/langs_widget.inc" --></div>
		</div>
		<div id="image-container">
			<div>
			</div>		
		</div>
	</div>