<table class="tableHeader" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td class="tdHeaderSX"><!-- #include virtual="/common/include/MenuFruizione.inc" --></td>
		<td align="left" class="tdHeaderBott"><a href="mailto:info@raro26.com" title="info@raro26.com" onMouseOver="MM_swapImage('header_mail','','<%=Application("baseroot")&"/templates/templateContatti2/img/header_mail_on.gif"%>',1)" onMouseOut="MM_swapImgRestore()"><img src="<%=Application("baseroot")&"/templates/templateContatti2/img/header_mail.gif"%>" border="0" align="left" id="header_mail" name="header_mail"/></a></td>
		<td align="right"><img src="<%=Application("baseroot")&"/common/img/logo_raro26_internal.jpg"%>" border="0" align="bottom"/></td>
	</tr>
    <!--
      <tr>
        <td align="left" class="tdHeaderBott"><a href="mailto:info@raro26.com" title="info@raro26.com" onMouseOver="MM_swapImage('header_mail','','<%=Application("baseroot")&"/templates/templateContatti2/img/header_mail_on.gif"%>',1)" onMouseOut="MM_swapImgRestore()"><img src="<%=Application("baseroot")&"/templates/templateContatti2/img/header_mail.gif"%>" border="0" align="left" id="header_mail" name="header_mail"/></a></td>
        </tr>
        -->
</table>