<!-- #include virtual="/common/include/Objects/GUIDClass.asp" -->
<!-- #include virtual="/common/include/Objects/UtilClass.asp" -->
<!-- #include virtual="/common/include/Objects/Base64Class.asp" -->
<!-- #include virtual="/common/include/Objects/CacheClass.asp" -->
<!-- #include virtual="/common/include/Objects/DBManagerClass.asp" -->
<!-- #include virtual="/common/include/Objects/CountryClass.asp" -->
<!-- #include virtual="/common/include/Objects/UserPreferenceClass.asp" -->
<!-- #include virtual="/common/include/Objects/UserClass.asp" -->
<!-- #include virtual="/common/include/Objects/CategoryClass.asp" -->
<!-- #include virtual="/common/include/Objects/MenuClass.asp" -->
<!-- #include virtual="/common/include/Objects/ExceptionClass.asp" -->
<!-- #include virtual="/common/include/Objects/LanguageClass.asp" -->
<!-- #include virtual="/common/include/Objects/TargetClass.asp" -->
<!-- #include virtual="/common/include/Objects/LogClass.asp" -->
<!-- #include virtual="/common/include/Objects/Page4TemplateClass.asp" -->
<!-- #include virtual="/common/include/Objects/TemplateClass.asp" -->
<!-- #include virtual="/common/include/Objects/ImageUploadClass.asp" -->
<%
'<!--nsys-editinc2-->
%>
<!-- #include virtual="/common/include/Objects/TaxsClass.asp" -->
<!-- #include virtual="/common/include/Objects/TaxsGroupClass.asp" -->
<!-- #include virtual="/common/include/Objects/PaymentClass.asp" -->
<!-- #include virtual="/common/include/Objects/PaymentFieldClass.asp" -->
<!-- #include virtual="/common/include/Objects/PaymentModuleClass.asp" -->
<!-- #include virtual="/common/include/Objects/PaymentTransactionClass.asp" -->
<!-- #include virtual="/common/include/Objects/BillsClass.asp" -->
<!-- #include virtual="/common/include/Objects/CurrencyClass.asp" -->

<!-- #include virtual="/common/include/Objects/UserGroupClass.asp" -->
<!-- #include virtual="/common/include/Objects/VoucherClass.asp" -->
<!-- #include virtual="/common/include/Objects/MarginDiscountClass.asp" -->
<!-- #include virtual="/common/include/Objects/BusinessRulesClass.asp" -->
<!-- #include virtual="/common/include/Objects/File4ProductsClass.asp" -->
<!-- #include virtual="/common/include/Objects/ProductsClass.asp" -->
<!-- #include virtual="/common/include/Objects/Products4OrderClass.asp" -->
<!-- #include virtual="/common/include/Objects/Bills4OrderClass.asp" -->
<!-- #include virtual="/common/include/Objects/OrderClass.asp" -->
<%
'<!---nsys-editinc2-->
%>
<!-- #include virtual="/common/include/Objects/LocalizationClass.asp" -->

<!-- #include file="InitData.inc" -->