<title><%=langEditor.getTranslated("backend.page.title")%></title>
<meta name="autore" content="Neme-sys; email:info@neme-sys.org">

<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<%
Response.Charset="UTF-8"
Session.CodePage  = 65001
%>
<!--<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">-->
<%'Response.Charset="ISO-8859-1"%>

<link rel="stylesheet" href="<%=Application("baseroot") & "/editor/css/stile.css"%>" type="text/css">
